# Generated by Django 4.1.5 on 2023-03-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tag',
            new_name='tags',
        ),
    ]
